"use client";
import { motion } from "framer-motion";
import { Compass, Download, LocateFixed, Moon, Search, Sun, X } from "lucide-react";
import { useTheme } from "next-themes";
import type { POI } from "@/features/offline-pack/types";
import type { Instruction } from "@/features/navigation/instructions";

type Props = { query: string; onQuery: (value: string) => void; results: POI[]; onPick: (poi: POI) => void; onSetStart: (poi: POI) => void; destination?: POI; instructions: Instruction[]; status: string; progress: number; error?: string; updateAvailable: boolean; onDownload: () => void; following: boolean; onLocate: () => void; onStop: () => void };
export function NavigationSheet(props: Props) {
  const { resolvedTheme, setTheme } = useTheme(); const dark = resolvedTheme === "dark";
  return <motion.section drag="y" dragConstraints={{ top: -300, bottom: 0 }} dragElastic={.08} initial={{ y: 220 }} animate={{ y: 0 }} className="absolute bottom-0 left-0 right-0 z-10 rounded-t-[28px] border border-black/5 bg-white/95 px-4 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-3 shadow-[0_-12px_40px_rgba(0,0,0,.12)] backdrop-blur dark:border-white/10 dark:bg-[#17251f]/95">
    <div className="mx-auto mb-3 h-1.5 w-10 rounded-full bg-slate-300 dark:bg-slate-600" />
    <div className="flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-2xl bg-slate-100 px-3 py-3 dark:bg-white/10"><Search size={18} /><input value={props.query} onChange={(event) => props.onQuery(event.target.value)} placeholder="Search LASU landmarks" className="w-full bg-transparent text-sm outline-none placeholder:text-slate-500" /></div><button onClick={() => setTheme(dark ? "light" : "dark")} className="rounded-2xl bg-slate-100 px-3 dark:bg-white/10" aria-label="Toggle color theme">{dark ? <Sun size={19} /> : <Moon size={19} />}</button></div>
    {props.status !== "ready" && <div className="mt-3 rounded-2xl bg-emerald-950 p-3 text-white"><div className="flex items-center gap-2 text-sm font-medium"><Download size={17} /> {props.status === "downloading" ? `Downloading map — ${Math.round(props.progress * 100)}%` : "Take LASU offline"}</div><p className="mt-1 text-xs text-emerald-100">Download the campus map and walking routes once, then navigate without data.</p>{props.status !== "downloading" && <button onClick={props.onDownload} className="mt-3 rounded-xl bg-white px-3 py-2 text-xs font-bold text-emerald-950">Download LASU map</button>}{props.error && <p className="mt-2 text-xs text-red-200">{props.error}</p>}</div>}
    {props.updateAvailable && props.status === "ready" && <div className="mt-3 flex items-center justify-between rounded-xl bg-amber-100 p-3 text-xs text-amber-950 dark:bg-amber-300"><span>A newer campus map is available.</span><button onClick={props.onDownload} className="font-bold underline">Update</button></div>}
    {props.destination && <div className="mt-3 rounded-2xl bg-emerald-50 p-3 dark:bg-emerald-900/30"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-300">Destination</p><p className="font-semibold">{props.destination.name}</p></div><button onClick={props.onStop} aria-label="Clear route"><X size={18} /></button></div>{props.instructions.slice(0, 2).map((item) => <p key={item.at} className="mt-2 flex gap-2 text-sm"><Compass size={16} className="shrink-0 text-emerald-600" />{item.text}</p>)}</div>}
    {props.results.length > 0 && <div className="mt-3 max-h-40 overflow-auto">{props.results.map((poi) => <div key={poi.id} className="flex items-center gap-2 border-b border-slate-200 py-2 last:border-0 dark:border-white/10"><button onClick={() => props.onPick(poi)} className="flex min-w-0 flex-1 items-center justify-between text-left text-sm"><span className="truncate">{poi.name}<span className="ml-2 text-xs text-slate-500">{poi.category}</span></span><Compass size={15} /></button><button onClick={() => props.onSetStart(poi)} className="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-medium dark:bg-white/10">Start</button></div>)}</div>}
    <button onClick={props.onLocate} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-emerald-700/30 py-2 text-sm font-medium text-emerald-800 dark:text-emerald-300"><LocateFixed size={16} />{props.following ? "Following your location" : "Use my location"}</button>
  </motion.section>;
}
